### ISSUE TITLE
tips.md removed?

### ISSUE THREAD

**Issue by stevestock** [OpenToAllCTF/OpenToAllCTF.github.io#2]
why was [tips.md](https://github.com/OpenToAllCTF/OpenToAllCTF.github.io/blob/62a70bb718e1bc4f1d53d3859ebc6126db98fa2a/tips.md) removed in recent updates?  I thought this was a helpful reference... has it been moved somewhere else?

**Comment by Corb3nik** [comment]
Hi @stevestock :)

We've moved the content to : https://github.com/OpenToAllCTF/tips
